<?php
$currentProduct = $block->getCurrentProduct();

$finalPrice = $currentProduct->getFinalPrice();
$dataCollection = $block->getModelData();
$onlyBankCode = $block->getOnlyBankCode();
// $block->test();

// $minEmi = [];
?>

<div id="popup-modal">
    <div id="json_out">

    </div>
    <div id="element" class="collapsibleContainer" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
            <div class="collapsibleTab" data-role="collapsible">
                <div data-role="trigger">
                    <!-- ko foreach: bankNameObservable() -->
                        <span data-bind="text: code"></span>
                    <!-- /ko -->
                </div>
            </div>
            <div class="collapsibleContent" data-role="content">
                <table id="emitable">
                    <thead>
                        <tr>
                            <th>EMI Plans</th>
                            <th>Interest(pa)</th>
                            <th>Final Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        <tr>
                            <td>Test</td>
                            <td>Test</td>
                            <td>Test</td>
                        </tr>
                    </tbody>
                </table>
            </div>
    </div> 
</div>

<?php if($block->isEnabled()): ?>
    <p id="emiBlock">Emi Starts From</p>
<?php endif; ?>

<script>

require(
    [
        'jquery',
        'ko'
    ],
    function ($, ko) 
    {
        $('body').on('click', '#emiBlock', function () {

            // var self = $(this);
            var url = "<?php echo $block->getUrl() . 'emidetails/index/JsonData' ?>";
            // console.log(url);
            try {

                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    // showLoader: true,
                    success: function (data) {

                        let bankNames = data['BankNameTest'];
                        let bankCodes = data['getOnlyBankCode'];
                        let emiPlans = data['EMI_Plan'];
                        getValues(bankNames, bankCodes, emiPlans);
                        // getBankFullName(bankcode)
                        getBankFullName(bankCodes);
                        ko.applyBindings(new TestViewModel());
                        // test();
                        // let test = bankNames.map(a => console.log(a))

                        // console.log(bankNames);
                    }
                });
            } 
            catch (e) {}

        });

        // let bankNameObservable = ko.observableArray([]);
        // let emiPlanObservable = ko.observableArray([]);

        function getValues(bankNames, bankCodes, emiPlans) {
            this.bankNames = bankNames;
            this.bankCodes = bankCodes;
            this.emiPlans = emiPlans;
        }

        function getBankFullName(bankCodes) {
            bankCodes.map(code => getBankDetails(code))
        }

        function getBankDetails(code) {
            // console.log(this.bankNames[code]);
            // console.log(this.emiPlans[code]);
            // $('.bankname').html(this.bankNames[code]);
            bankNameObservable.push({
                code: this.bankNames[code]
            })

            // console.log(bankNameObservable());

            emiPlanObservable.push({
                plan: this.emiPlans[code]
            })

            // console.log(emiPlanObservable);
        }



        function TestViewModel() {
            var self = this;
            self.bankNameObservable = ko.observableArray([]);
            // self.emiPlanObservable = ko.observableArray([]);
            // console.log(bankNameObservable()[0]);
            // self.banks = bankNameObservable();
            // self.plans = emiPlanObservable();

            return self.bankNameObservable;
        }

        // function test() {
        //     console.log(bankNameObservable());
        // }
    }
);

</script>