<?php
$currentProduct = $block->getCurrentProduct();

$finalPrice = $currentProduct->getFinalPrice();
$dataCollection = $block->getModelData();
$onlyBankCode = $block->getOnlyBankCode();
?>

<?php if($block->isEnabled()): ?>
    <p id="emiBlock">Emi Starts From</p>
<?php endif; ?>

<div id="popup-modal">

    <?php if($currentProduct): ?>
        <h1><?php $finalPrice; ?></h1>
        <div id="element" class="collapsibleContainer" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": true}}'>
            <?php foreach ($onlyBankCode->getData() as $bankcode): ?>
                <div class="collapsibleTab" data-role="collapsible">
                    <div data-role="trigger">
                        <?php foreach ($block->getBankName($bankcode['bank_code']) as $bankName): ?>
                            <span><?php echo $bankName['bank_name']; ?></span>
                        <?php endforeach; ?>
                    </div>
                </div>
                <div class="collapsibleContent" data-role="content">
                        <table id="emitable">
                            <thead>
                                <tr>
                                    <th>Months</th>
                                    <th>Interest</th>
                                    <th>Final Amount</th>
                                </tr>
                            </thead>
                            <tbody>

                        <?php foreach ($block->getEmiPlans($bankcode['bank_code'])->getData() as $emi): ?>
                            
                            <tr>
                                <td><?php echo $emi['month']; ?></td>
                                <td><?php echo $emi['interest']; ?></td>
                                <td><?php echo "1212"; ?></td>
                            </tr>
                            
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>    
</div>