<div id="emi-component" data-bind="scope:'emicomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <?php $data = "Test"; ?>
    <script type="text/x-magento-init">
    {
        "#emi-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "emicomponent": {
                        "component": "Ambab_EmiCalculator/js/emi-component",
                        "data": "<?= $data; ?>"
                    }
                }
            }
        }
    }
    </script>
</div>